### ISSUE TITLE
Sub-directory per players in same port.

### ISSUE THREAD

**Issue by KaffinPX** [PrismarineJS/prismarine-viewer#177]

**Comment by rom1504** [comment]
Give more information

**Comment by KaffinPX** [comment]
Like this: localhost/bot/KaffinPX for prismarine-viewer not main directory.

**Comment by fox3000foxy** [comment]
Yes
Its my request Kaffin

**Comment by KaffinPX** [comment]
I have a code but it crashes mostly, we need to integrate it to viewer

**Comment by fox3000foxy** [comment]
youre right its that

localhost:8080/bot/Fox3000
for have fp view of Fox3000

**Comment by rom1504** [comment]
Please give more information
What is the use case ?
What do you expect this to do

**Comment by AwesomestCode** [comment]
I’ll clarify (they explained to me in Discord). Basically, since Heroku doesn’t allow for them to bind to multiple ports and they want to have multiple bots (each with its own viewer), the obvious answer is to use subdirectories (like https://example.com/bot-01 https://example.com/bot-02 and https://example.com/bot-03)

**Comment by fox3000foxy** [comment]
yeah its that

**Comment by rom1504** [comment]
I think it would make sense for you to directly use the core lib to set that up
You can use https://github.com/PrismarineJS/prismarine-viewer/blob/master/lib/mineflayer.js as an example
