### ISSUE TITLE
Colored Wool

### ISSUE THREAD

**Issue by JuuulianUwU** [PrismarineJS/prismarine-viewer#271]
Heyho!

I really love this library. However I have one big issue. Im currently displaying a small r/place event. 

I've setup the viewer and all works fine. 

However wool blocks do only get displayed in white

Example:
![unknown (1)](https://user-images.githubusercontent.com/70039325/173199461-59756747-f290-46c4-93bc-ace10d2a294a.png)

It should look like this: (without the texturepack ofc)
<img width="706" alt="Screenshot 2022-06-11 200040" src="https://user-images.githubusercontent.com/70039325/173199526-d3716e46-a14e-4e77-bb64-d7927d7c00c9.png">

Is there a way to fix this?

Cheers,
Julian S.

**Comment by Karang** [comment]
what version are you using ?

**Comment by JuuulianUwU** [comment]
> what minecraft version are you using ?

1.8.9

**Comment by Karang** [comment]
Ok, that's what I suspected. If you can, you should use a more recent version, as later versions have a separate texture for each color, it should render properly.

The problem is that in 1.8 wool only have one texture and is colored in the code, through the tints. It's not currently implemented, but shouldn't be too hard to add, if you want to do a pull request: https://github.com/PrismarineJS/prismarine-viewer/blob/master/viewer/lib/models.js#L261

**Comment by JuuulianUwU** [comment]
Thanks, I've upgraded the client to 1.18.2 and its working now.

Cheers,
Julian S.

**Comment by 182exe** [comment]
> The problem is that in 1.8 wool only have one texture and is colored in the code, through the tints. It's not currently implemented, but shouldn't be too hard to add, if you want to do a pull request: https://github.com/PrismarineJS/prismarine-viewer/blob/master/viewer/lib/models.js#L261

That's false... 1.8 wool has 16 different textures.
