### ISSUE TITLE
Replace world.js by prismarine-world

### ISSUE THREAD

**Issue by rom1504** [PrismarineJS/prismarine-viewer#31]
https://github.com/PrismarineJS/prismarine-viewer/blob/master/src/world.js

would it make sense ?

**Comment by Karang** [comment]
yes it could be done
but there is some subtilities:
* world.js is living in the worker thread, in the browser
* https://github.com/PrismarineJS/prismarine-viewer/blob/master/src/world.js#L20 addColumn take the json and build the chunk

The current architecture for rendering chunks is:
```
        node.js                browser, main thread               worker thread
mineflayer / p-world  -----------> passthrough ---------------> world.js (decode json/ store chunk)
                                   store mesh <---------------- build mesh geometry
```

In the future, I'd like to have multiple worker thread (a pool) to speedup the meshing but the problem is to have a single world shared by all workers without a big cost of communication. Worker thread have shared memory but this would need a lot of adaptation, a simpler solution would be to have a world instance per worker thread (but it duplicate all chunks and use more memory).

**Comment by Karang** [comment]
Finally went for the simpler solution (having a world instance per worker).

world.js have evolved a bit and now does some rendering specific caching of blocks, while the caching can be moved outside, I don't see the benefit of using a full pworld instance here as it brings a lot of unneeded functionalities.

We should use pworld on the server side to have a single interface, but this is tracked in an other issue: https://github.com/PrismarineJS/prismarine-viewer/issues/10

**Comment by rom1504** [comment]
Ok, let's go in that direction then. We can always revaluate this later if things change
